
#网站设置 详细https://github.com/mojombo/jekyll/wiki/configuration
markdown:         rdiscount
pygments:         true
paginate:         4
#permalink: /:year/:month/:day/:title
permalink: 		  date

title:            Henter
url:              
feed:             atom.xml
author:
    name:         Henter
    email:        henter@henter.me
    description:  "The one theme is another web theme design by PIZn."

follow:
    email:        henter@henter.me
    github:       https://github.com/henter
    twitter:      http://www.twitter.com/henterchow
    google:       https://plus.google.com/107483619032085919305
    facebook:     http://facebook.com/henterchow
    weibo:     	  http://weibo.com/henter


indexContent:     true


blogName:         Henter
blogDesc:         RD at <a href="http://zuo.com/@henter" target="_blank">zuo.com</a>
favicon:          favicon.ico
theme:            henter-diandian

disqus:           henter

copyright:        Copyright © 2008-2013 Henter All rights reserved.
